spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: edulinknotification@gmail.com
    password: xvbsmmyfnfowdjsu

    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  #    debug: true
  datasource:
    url: jdbc:postgresql://edulinkpostgressql.postgres.database.azure.com:5432/edu_link
    username: edulink
    password: root@2002
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
#    show-sql: true
