spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: edulinknotification@gmail.com
    password: xvbsmmyfnfowdjsu

    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
#    debug: true
  datasource:
    url: jdbc:mariadb://localhost:3306/edu_link
    username: root
    password: 2004
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
